# Generated by Django 5.0.4 on 2024-04-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('foodplan', '0008_alter_subscription_menu_type_alter_subscription_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
