# Generated by Django 5.0.4 on 2024-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='caloricity',
            new_name='energy',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='Углеводы, г'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0, verbose_name='Жиры, г'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0, verbose_name='Белки, г'),
        ),
        migrations.AlterField(
            model_name='menutype',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
