# Generated by Django 5.0.4 on 2024-04-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0003_remove_recipe_menu_type_menutyperecipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.CreateModel(
            name='MealTypeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_type_recipes', to='foodplan.mealtype', verbose_name='Тип блюда')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_type_recipes', to='foodplan.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'тип блюда',
                'verbose_name_plural': 'Рецепты по типам блюд',
            },
        ),
        migrations.DeleteModel(
            name='MenuTypeRecipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='foodplan.menutype', verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ManyToManyField(related_name='recipes', through='foodplan.MealTypeRecipe', to='foodplan.mealtype', verbose_name='Тип блюда'),
        ),
    ]
