# Generated by Django 5.0.4 on 2024-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0005_remove_recipe_menu_type_menutyperecipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='people',
            field=models.IntegerField(default=1, verbose_name='Количество порций'),
        ),
    ]
