# Generated by Django 5.0.4 on 2024-04-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('foodplan', '0006_recipe_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_quantity', models.IntegerField(verbose_name='Количество персон')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, руб.')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='foodplan.menutype', verbose_name='Тип меню')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='account.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionMealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_meal_types', to='foodplan.mealtype', verbose_name='Тип блюда')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_meal_types', to='foodplan.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Тип блюда подписки',
                'verbose_name_plural': 'Типы блюд подписки',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='meal_type',
            field=models.ManyToManyField(related_name='subscriptions', through='foodplan.SubscriptionMealType', to='foodplan.mealtype', verbose_name='Тип блюда'),
        ),
    ]
