# Generated by Django 5.0.4 on 2024-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0008_alter_subscription_menu_type_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
