# Generated by Django 5.0.4 on 2024-04-18 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0010_subscriptionallergy_subscription_allergies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('multiplier', models.IntegerField(default=1, verbose_name='Множитель')),
                ('attempt', models.IntegerField(default=1, verbose_name='Попытка')),
                ('reaction', models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится'), ('neutral', 'Нейтрально')], default='neutral', max_length=7, verbose_name='Реакция')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Действует')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recipes', to='foodplan.mealtype', verbose_name='Тип блюда')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recipes', to='foodplan.recipe', verbose_name='Рецепт')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recipes', to='foodplan.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рецепт пользователя',
                'verbose_name_plural': 'Рецепты пользователей по дням',
            },
        ),
    ]
