# Generated by Django 4.2.11 on 2024-04-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0011_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='waiting_for_payment', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
