# Generated by Django 4.2.11 on 2024-04-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0014_unit_ingredient_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='foodplan.unit', verbose_name='Единица измерения'),
        ),
    ]
