# Generated by Django 4.2.11 on 2024-04-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0015_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='mass',
        ),
    ]
