# Generated by Django 4.2.11 on 2024-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0016_remove_ingredient_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='mass',
            field=models.IntegerField(default=1, verbose_name='Масса, г'),
        ),
    ]
